# Generated by Django 4.2.6 on 2024-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='withdraw_approve',
            field=models.BooleanField(default=False),
        ),
    ]
